# Generated by Django 5.1.3 on 2024-11-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0002_alter_reserva_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.CharField(max_length=200),
        ),
    ]
