# Generated by Django 5.1.3 on 2024-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
