# Generated by Django 5.1.3 on 2024-11-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0002_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.CharField(help_text='Duración en minutos', max_length=2),
        ),
    ]
